# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R-TJDnBLkvqtqpLqilzAlLx--AUIbC3i
"""

# clone darknet repo
!git clone https://github.com/AlexeyAB/darknet

# Commented out IPython magic to ensure Python compatibility.
# change makefile to have GPU and OPENCV enabled
# %cd darknet
!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/' Makefile
!sed -i 's/CUDNN_HALF=0/CUDNN_HALF=1/' Makefile

# verify CUDA
!/usr/local/cuda/bin/nvcc --version

# make darknet (builds darknet so that you can then use the darknet executable file to run or train object detectors)
!make

# Commented out IPython magic to ensure Python compatibility.
# define helper functions
def imShow(path):
  import cv2
  import matplotlib.pyplot as plt
#   %matplotlib inline

  image = cv2.imread(path)
  height, width = image.shape[:2]
  resized_image = cv2.resize(image,(3*width, 3*height), interpolation = cv2.INTER_CUBIC)

  fig = plt.gcf()
  fig.set_size_inches(18, 10)
  plt.axis("off")
  plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
  plt.show()

# use this to upload files
def upload():
  from google.colab import files
  uploaded = files.upload() 
  for name, data in uploaded.items():
    with open(name, 'wb') as f:
      f.write(data)
      print ('saved file', name)

# use this to download a file  
def download(path):
  from google.colab import files
  files.download(path)

# Commented out IPython magic to ensure Python compatibility.
# %cd ..
from google.colab import drive
drive.mount('/content/gdrive')

# Commented out IPython magic to ensure Python compatibility.
# %cd darknet

!ln -s /content/gdrive/My\ Drive/ /mydrive
!ls /mydrive

!cp /mydrive/YOLO/generate_test.py ./
!cp /mydrive/YOLO/generate_train.py ./
!cp /mydrive/YOLO/getannot.py ./
!cp /mydrive/YOLO/getvalid.py ./

!cp /mydrive/YOLO/yolov4-obj.cfg ./cfg
!cp /mydrive/YOLO/obj.names ./data
!cp /mydrive/YOLO/obj.data ./data
!cp /mydrive/YOLO/train.txt ./data
!cp /mydrive/YOLO/valid.txt ./data

!unzip /mydrive/YOLO/annot.zip
!unzip /mydrive/YOLO/obj.zip -d ./data
!unzip /mydrive/YOLO/test.zip -d ./data
!mkdir ./data/valid

!python getvalid.py

!python getannot.py

#get test.txt
!python generate_test.py

!./darknet detector train data/obj.data cfg/yolov4-obj.cfg /mydrive/YOLO/backup/yolov4-obj_last.weights -dont_show -map

!./darknet detector test data/obj.data cfg/yolov4-obj.cfg /mydrive/YOLO/backup/yolov4-obj_last.weights -ext_output -dont_show -out result.json < data/test.txt

download('result.json')
#convert to HW2 format
!python getResult.py